### ISSUE TITLE
mnist_auto_encoder test failing with pyeddl

### ISSUE THREAD

**Issue by ilveroluca** [deephealthproject/docker-libs#36]
The `mnist_auto_encoder` has been failing to run on the pyeddl image, apparently because the current example asks for too much memory for the resources available on the CI infrastructure.

```
Batch 60 dense6 loss[mean_squared_error]=0.082 metric[mean_squared_error]=0.082  -- 0.005 secs/batch
0.319 secs/epoch
Predict 60000 samples
Traceback (most recent call last):
  File "/usr/local/src/pyeddl/examples/NN/1_MNIST/mnist_auto_encoder.py", line 69, in <module>
    main(parser.parse_args(sys.argv[1:]))
  File "/usr/local/src/pyeddl/examples/NN/1_MNIST/mnist_auto_encoder.py", line 60, in main
    tout = eddl.predict(net, [x_train])
  File "/usr/local/lib/python3.6/dist-packages/pyeddl/eddl.py", line 398, in predict
    return _eddl.predict(m, in_)
RuntimeError: Error allocating 179.44MB in Tensor::resize

Removing temp container instance 'pyeddl-toolkit-ZGldSPjcKIEGSmHeGAq1Ay52OIjslyWu'... DONE
```

Example of a failed build:  https://jenkins-master-deephealth-unix01.ing.unimore.it/job/DeepHealth-Docker/job/pyeddl/81/consoleFull

**Comment by simleo** [comment]
Raised upstream: https://github.com/deephealthproject/eddl/issues/208
